# Generated by Django 3.1.4 on 2021-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=64)),
                ('item_description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
    ]
