# Generated by Django 3.1.4 on 2021-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210103_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
