# Generated by Django 3.1.4 on 2021-01-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=64)),
                ('item_description', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bid'),
        ),
    ]
