# Generated by Django 3.1.4 on 2021-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210103_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=22),
            preserve_default=False,
        ),
    ]
